/*
 * This source file was generated by the Gradle 'init' task
 */
package org.blog;

import org.junit.Test;
import static org.junit.Assert.*;

//public class AppTest {
//    @Test public void appHasAGreeting() {
//        App classUnderTest = new ();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//    }
//}
