spring.application.name=backend_boot
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/myblog
spring.datasource.username=postgres
spring.datasource.password=postgres

# ???????? Spring Data JDBC ???????????
spring.data.jdbc.repositories.enabled=true

spring.sql.init.mode=always
