DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post_images;
DROP TABLE IF EXISTS posts;

-- Таблица с постами для H2 (правильный синтаксис IDENTITY)
CREATE TABLE IF NOT EXISTS posts(
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    title VARCHAR(256) NOT NULL,
                                    text VARCHAR(1000) NOT NULL,
                                    likes_count INTEGER DEFAULT 0,
                                    tags VARCHAR(256) ARRAY DEFAULT ARRAY[]
);

-- Таблица с комментариями
CREATE TABLE IF NOT EXISTS comments(
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       text VARCHAR(100) NOT NULL,
                                       post_id INTEGER,
                                       FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

-- Таблица с изображениями постов
CREATE TABLE IF NOT EXISTS post_images(
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          post_id INTEGER NOT NULL,
                                          file_name VARCHAR(256) NOT NULL
);